PARAMETER offset.

SET iPAlt TO ADDONS:TR:IMPACTPOS:TERRAINHEIGHT.
LOCK v to SHIP:VERTICALSPEED.
LOCK a to SHIP:MAXTHRUST/SHIP:MASS - BODY:MU/(BODY:RADIUS+iPAlt)^2.
LOCK rO TO ALT:RADAR-offset.
LOCK d TO v^2/(2*a).
LOCK t TO rO/abs(v).

RCS ON.
BRAKES ON.
SAS OFF.
LOCK STEERING TO SRFRETROGRADE.
WHEN t<3 THEN {GEAR ON.}

WAIT UNTIL d/rO>=0.95.
LOCK THROTTLE TO d/rO.

WAIT UNTIL v>-0.01.
LOCK THROTTLE TO 0.
UNLOCK ALL.
RCS OFF.
