PARAMETER isp.
SET n TO NEXTNODE.
SET dv TO n:DELTAV.
LOCK m TO ship:Mass.
LOCK STEERING TO LOOKDIRUP(n:DELTAV,SUN:POSITION).
WAIT UNTIL n:ETA <= (m - m/(CONSTANT:E^((dv:MAG/2)/(isp*9.81)))) / (SHIP:MAXTHRUST/(isp*9.81)).
LOCK THROTTLE TO n:DELTAV:MAG/(SHIP:MAXTHRUST/m).
UNTIL FALSE{
IF VDOT(dv, n:DELTAV) < 0{
UNLOCK ALL.
SET SHIP:CONTROL:PILOTMAINTHROTTLE TO 0.
BREAK.
}
WAIT 0.
}